### PR TITLE
Fix docker compose file for midjourney-proxy

### PR DESCRIPTION
**Pull request by KennyDizi**
Fix docker compose file for midjourney-proxy

### CODE REVIEW

**Comment by KennyDizi** [comment]
Hi @Licoy Pls take a look at this PR to fix docker compose issue with midjourney-proxy

**Comment by Licoy** [comment]
need proxy envs

**Comment by KennyDizi** [comment]
The PR has been updated with update proxy envs @Licoy

**Comment by Licoy** [comment]
nonono! midjourney-proxy need midjourney-proxy envs, is not chatgpt-next-web envs

**Pull request closed without merging**
